# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_service', '0002_auto_20160630_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_service.Pizza'),
        ),
    ]
