# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_service', '0003_order_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_service.Client'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='prise',
            field=models.IntegerField(),
        ),
    ]
