# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_service', '0005_auto_20160630_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientorders',
            name='order_ptr',
        ),
        migrations.DeleteModel(
            name='ClientOrders',
        ),
    ]
