# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_service', '0006_auto_20160630_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrders',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pizza_service.Order')),
            ],
            bases=('pizza_service.order',),
        ),
    ]
