# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_service', '0012_auto_20160702_1800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
