# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('brand', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('lastOrder', models.DateField()),
                ('orders', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('available', models.BooleanField(default=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_service.Auto')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.DateTimeField(auto_created=True)),
                ('source', models.CharField(max_length=254)),
                ('destination', models.CharField(max_length=254)),
                ('picked', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivered', models.DateTimeField(blank=True, default=None, null=True)),
                ('distance', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_service.Client')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxi_service.Driver')),
            ],
        ),
    ]
